//
// Created by Dolores on 2026/8/8.
//

#ifndef SUMMER_SUMMER_H
#define SUMMER_SUMMER_H

//烧录云台or底盘
#define GIMBAL
//#define CHASSIS

#define CAN_HEARTBEAT_MASK 0xFF
#define CAN_SLOW_SEND_PERIOD_MS 100
#define WHEEL_MAX_RPM 200.0f
#define SELF_TEST_PHASE_DURATION_MS 3000
#define SELF_TEST_SERVO_DURATION_MS 2000
#define STATUS_SELF_TEST 0x08
#define STATUS_SYSTEM_OK 0x00
#define STATUS_CAN_ERROR 0x01

#endif //SUMMER_SUMMER_H
